image:
  file: .gitpod.Dockerfile
ports:
  - name: VS Code Browser
    port: 9888
    description: Instance where you can test your changes.
    onOpen: open-browser
tasks:
  - init: |
      yarn
      yarn server:init
    command: |
      gp sync-done init
      export NODE_ENV=development
      export VSCODE_DEV=1
      yarn gulp watch-init
    name: watch app
  - command: |
      export NODE_ENV=development
      export VSCODE_DEV=1
      gp sync-await init
      cd ./extensions
      yarn watch
    name: watch extension
  - command: |
      export NODE_ENV=development
      export VSCODE_DEV=1
      gp sync-await init
      ./scripts/code-server.sh --without-connection-token
    name: run app
    openMode: split-right
github:
  prebuilds:
    pullRequestsFromForks: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint
